language: python
python:
  - "2.7"

# Install dependencies
install: "pip install -r requirements.txt"

notifications:
    email: false

# command to run tests
script:
    - cd include/test && py.test

after_script:
    -  rm include/tests/test-blci/blci_deps.json

branches:
    only:
        disa-dev
